// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kind.Outputs
{

    [OutputType]
    public sealed class ClusterKindConfigNodeExtraMount
    {
        public readonly string? ContainerPath;
        public readonly string? HostPath;
        public readonly string? Propagation;
        public readonly bool? ReadOnly;
        public readonly bool? SelinuxRelabel;

        [OutputConstructor]
        private ClusterKindConfigNodeExtraMount(
            string? containerPath,

            string? hostPath,

            string? propagation,

            bool? readOnly,

            bool? selinuxRelabel)
        {
            ContainerPath = containerPath;
            HostPath = hostPath;
            Propagation = propagation;
            ReadOnly = readOnly;
            SelinuxRelabel = selinuxRelabel;
        }
    }
}
