// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kind.Outputs
{

    [OutputType]
    public sealed class ClusterKindConfigNode
    {
        public readonly ImmutableArray<Outputs.ClusterKindConfigNodeExtraMount> ExtraMounts;
        public readonly ImmutableArray<Outputs.ClusterKindConfigNodeExtraPortMapping> ExtraPortMappings;
        public readonly string? Image;
        public readonly ImmutableArray<string> KubeadmConfigPatches;
        public readonly ImmutableDictionary<string, string>? Labels;
        public readonly string? Role;

        [OutputConstructor]
        private ClusterKindConfigNode(
            ImmutableArray<Outputs.ClusterKindConfigNodeExtraMount> extraMounts,

            ImmutableArray<Outputs.ClusterKindConfigNodeExtraPortMapping> extraPortMappings,

            string? image,

            ImmutableArray<string> kubeadmConfigPatches,

            ImmutableDictionary<string, string>? labels,

            string? role)
        {
            ExtraMounts = extraMounts;
            ExtraPortMappings = extraPortMappings;
            Image = image;
            KubeadmConfigPatches = kubeadmConfigPatches;
            Labels = labels;
            Role = role;
        }
    }
}
